// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeJn8xW5fTgEVuVI9gElCF42G4PUYbgdY',
    appId: '1:412560928338:web:1f589fe32eb9f29c9bb98b',
    messagingSenderId: '412560928338',
    projectId: 'authentication-f6863',
    authDomain: 'authentication-f6863.firebaseapp.com',
    storageBucket: 'authentication-f6863.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcwoYS2nUZj1j9bkMPfcXrdjJ0j9dHop4',
    appId: '1:412560928338:android:e52b2904be46e38e9bb98b',
    messagingSenderId: '412560928338',
    projectId: 'authentication-f6863',
    storageBucket: 'authentication-f6863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI1MVfrLsfbSg3GrxHluDpjiNHPc5mtU8',
    appId: '1:412560928338:ios:25114e55b91257359bb98b',
    messagingSenderId: '412560928338',
    projectId: 'authentication-f6863',
    storageBucket: 'authentication-f6863.appspot.com',
    androidClientId: '412560928338-u37fbv5selprtalgujvo9ba9ue86mjjs.apps.googleusercontent.com',
    iosClientId: '412560928338-a26vh3l6bsdaculibpnrd36k1a5rp2te.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI1MVfrLsfbSg3GrxHluDpjiNHPc5mtU8',
    appId: '1:412560928338:ios:8712010f05ec1d679bb98b',
    messagingSenderId: '412560928338',
    projectId: 'authentication-f6863',
    storageBucket: 'authentication-f6863.appspot.com',
    androidClientId: '412560928338-u37fbv5selprtalgujvo9ba9ue86mjjs.apps.googleusercontent.com',
    iosClientId: '412560928338-6v7v28740ckge3e9i374642oh1o68s7h.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleauth.RunnerTests',
  );
}
